const AvatarList =[
    {
        "id":1,
        "url":1,
        "nombre":"Noha",
    },
    {
        "id":2,
        "url":2,
        "nombre":"James",
    },
    {
        "id":3,
        "url":3,
        "nombre":"Ethan",
    },
    {
        "id":4,
        "url":4,
        "nombre":"Jayden",
    },
    {
        "id":5,
        "url":5,
        "nombre":"Emma",
    },
    {
        "id":6,
        "url":6,
        "nombre":"Sophia",
    },
    {
        "id":7,
        "url":7,
        "nombre":"Chloe",
    },
    {
        "id":8,
        "url":8,
        "nombre":"Lily",
    }
]
export {AvatarList}