const AnimalsListeningAnimals =[
    {
        "id":1,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/thecowis_wytwid.mp3',
        "respuestaAcertada":4,
        'nombre':'Quiz Animals',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Green - Red',
            },
            {
                "id":2,
                "respuesta":'Blue - Yellow',
            },
            {
                "id":3,
                "respuesta":'Pink - Purple',
            },
            {
                "id":4,
                "respuesta":'Black - White',
            }
        ],
    },
    {
        "id":2,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/theelephant_bqefsy.mp3',
        "respuestaAcertada":3,
        'nombre':'Quiz Animals',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Big',
            },
            {
                "id":2,
                "respuesta":'Herbivorous',
            },
            {
                "id":3,
                "respuesta":'Dangerous',
            },
            {
                "id":4,
                "respuesta":'Clever',
            }
        ],
    },
    {
        "id":3,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/thelionis_jh5p38.mp3',
        "respuestaAcertada":2,
        'nombre':'Quiz Animals',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Furry',
            },
            {
                "id":2,
                "respuesta":'Domestic',
            },
            {
                "id":3,
                "respuesta":'Dangerous',
            },
            {
                "id":4,
                "respuesta":'Aguile',
            }
        ],
    },
    {
        "id":4,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/animalisnotdomestic_voxan5.mp3',
        "respuestaAcertada":1,
        'nombre':'Quiz Animals',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Tiger',
            },
            {
                "id":2,
                "respuesta":'Dog',
            },
            {
                "id":3,
                "respuesta":'Bird',
            },
            {
                "id":4,
                "respuesta":'Sheep',
            }
        ],
    },
    {
        "id":5,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939581/questions/animalisfurry_cy3u19.mp3',
        "respuestaAcertada":4,
        'nombre':'Quiz Animals',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Cat',
            },
            {
                "id":2,
                "respuesta":'Dog',
            },
            {
                "id":3,
                "respuesta":'Mouse',
            },
            {
                "id":4,
                "respuesta":'All',
            }
        ],
    },
]
export {AnimalsListeningAnimals}