const QuestionsListeningOccupations =[
    {
        "id":1,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/whotravelintospace_vwjtiv.mp3',
        "respuestaAcertada":4,
        'nombre':'Quiz Occupations',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Fireman',
            },
            {
                "id":2,
                "respuesta":'Teacher',
            },
            {
                "id":3,
                "respuesta":'Painter',
            },
            {
                "id":4,
                "respuesta":'Astronaut',
            }
        ],
    },
    {
        "id":2,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939580/questions/whobaker_iagr7u.mp3',
        "respuestaAcertada":2,
        'nombre':'Quiz Occupations',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Doctor',
            },
            {
                "id":2,
                "respuesta":'Baker',
            },
            {
                "id":3,
                "respuesta":'Teacher',
            },
            {
                "id":4,
                "respuesta":'Nurse',
            }
        ],
    },
    {
        "id":3,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939581/questions/whodoctor_pcnp4e.mp3',
        "respuestaAcertada":1,
        'nombre':'Quiz Occupations',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Doctor',
            },
            {
                "id":2,
                "respuesta":'Baker',
            },
            {
                "id":3,
                "respuesta":'Teacher',
            },
            {
                "id":4,
                "respuesta":'Painter',
            }
        ],
    },
    {
        "id":4,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939581/questions/whofireman_u5rgak.mp3',
        "respuestaAcertada":1,
        'nombre':'Quiz Occupations',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Fireman',
            },
            {
                "id":2,
                "respuesta":'Teacher',
            },
            {
                "id":3,
                "respuesta":'Painter',
            },
            {
                "id":4,
                "respuesta":'Astronaut',
            }
        ],
    },
    {
        "id":5,
        'pregunta':'https://res.cloudinary.com/drqr9l8n4/video/upload/v1603939581/questions/whoteacher_rs0rqv.mp3',
        "respuestaAcertada":3,
        'nombre':'Quiz Occupations',
        "respuestas":[
            {
                "id":1,
                "respuesta":'Doctor',
            },
            {
                "id":2,
                "respuesta":'Baker',
            },
            {
                "id":3,
                "respuesta":'Teacher',
            },
            {
                "id":4,
                "respuesta":'Paiter',
            }
        ],
    },
]
export {QuestionsListeningOccupations}